# Generated by Django 3.2.7 on 2022-02-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloted_projects',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alloted_projects',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
