# Generated by Django 3.2.7 on 2022-02-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_mails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mails',
            new_name='Mailbox',
        ),
    ]
