# Generated by Django 3.2.7 on 2022-01-10 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_description', models.CharField(blank=True, max_length=20000)),
                ('qualification', models.CharField(max_length=10000)),
                ('NoOfEmployees', models.CharField(blank=True, max_length=50, null=True)),
                ('Designation', models.CharField(max_length=100)),
                ('amount_range', models.CharField(max_length=50)),
                ('DOB', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('location', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='images')),
                ('user_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_userid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=200000)),
                ('project_duration', models.CharField(max_length=10)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('price_range', models.CharField(blank=True, max_length=10, null=True)),
                ('skill_choice', models.CharField(choices=[('front-end', 'Front-end'), ('back-end', 'Back-end'), ('full-stack', 'Full-stack')], default='full-stack', max_length=10)),
                ('job_choice', models.CharField(choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time')], default='Fulltime', max_length=10)),
                ('category_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_category', to='core.category')),
                ('client_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_client', to='emp_app.profile_client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Rent_per_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('work_duration', models.IntegerField()),
                ('client_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_client', to='emp_app.profile_client')),
                ('developer_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_developer', to='developer_app.profile_dev')),
                ('work_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_workid', to='developer_app.work_dev')),
            ],
        ),
    ]
