# Generated by Django 3.2.7 on 2022-01-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_duration',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
