# Generated by Django 3.2.7 on 2022-01-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_alter_project_project_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
