# Generated by Django 3.2.7 on 2022-01-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_alter_project_project_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_client',
            name='company_description',
            field=models.TextField(blank=True, max_length=20000),
        ),
    ]
