# Generated by Django 3.2.7 on 2022-01-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_alter_profile_client_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(blank=True, max_length=20000),
        ),
    ]
