# Generated by Django 3.2.7 on 2022-01-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0005_alter_project_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
