# Generated by Django 3.2.7 on 2022-01-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_user', '0005_customuser_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
