# Generated by Django 3.2.7 on 2022-01-10 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_skill', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=10000)),
                ('work_experience', models.CharField(max_length=10)),
                ('past_project', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=200)),
                ('working_hours', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=10)),
                ('salary', models.CharField(max_length=10)),
                ('DOB', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('picture', models.ImageField(blank=True, upload_to='Images')),
                ('user_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_userid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work_dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rent_per_hours', models.IntegerField()),
                ('work_duration', models.CharField(max_length=10)),
                ('Date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('developer_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Work_dev_developerid', to='developer_app.profile_dev')),
            ],
        ),
    ]
